---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gvmd-pvc
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openvas-pvc
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-pvc
  namespace: {{ template "openvas.namespace" . }}
  labels:
    {{- include "openvas.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.psgvm.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.psgvm.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.psgvm.persistence.accessMode | quote }}
  storageClassName: {{ .Values.psgvm.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.psgvm.persistence.size | quote }}
